[build]
  command = "JEKYLL_ENV=production jekyll build"
  publish = "_site"

[context.deploy-preview]
  command = "JEKYLL_ENV=production jekyll build"
  publish = "_site"

[context.draft]
  command = "JEKYLL_ENV=staging jekyll build --drafts"
  publish = "_site"
